### ISSUE TITLE
add members to other projects?

### ISSUE THREAD

**Issue by markdav-is** [MVPStudio/k8#37]
@codegold79 and I both have Rancher projects and it would be cool if we could see each other's namepaces, etc.  I don't see a way to invite folks to other projects...  Any thoughts?

**Comment by markdav-is** [comment]
thanks @slively I think we got these all added.

**Comment by oliverdain** [comment]
@markdav-is not sure what you mean by "see". If you want to add other people to a project you can do that via the Rancher UI. If you mean you want containers running in one namespace to be able to talk to containers running in another namespace you can do that already - you just have to use the fully qualified service name (`<service>.<namespace>` as opposed to just `<service>`).

If this doesn't answer your questions maybe we should chat.

**Comment by oliverdain** [comment]
doh! I just saw that you closed this so maybe... never mind :)

**Comment by markdav-is** [comment]
this was for some spcific new members.... but they will still need to access services... so maybe that another ticket....
