### ISSUE TITLE
Standard WordPress Image

### ISSUE THREAD

**Issue by markdav-is** [MVPStudio/k8#55]
Let's support some great stuff!

- Backups (database and files)
- Auto-upgrade
- PhP My-Admin
- file access? no FTP!
- more to come!
 Have a real meeting the Ren

**Comment by oliverdain** [comment]
I think I'm going to create a new repo for this. That way we'll have a single repo that people can just fork to get a working Wordpress setup.

**Comment by oliverdain** [comment]
Will open bugs here: https://github.com/MVPStudio/standard-wordpress.git
